package com.themis.test.dao;

import com.themis.test.entity.user_t;
import com.themis.test.entity.user_tExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface user_tMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    long countByExample(user_tExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int deleteByExample(user_tExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int insert(user_t record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int insertSelective(user_t record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    List<user_t> selectByExample(user_tExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    user_t selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") user_t record, @Param("example") user_tExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int updateByExample(@Param("record") user_t record, @Param("example") user_tExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int updateByPrimaryKeySelective(user_t record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbg.generated Sat Sep 02 15:08:29 CST 2017
     */
    int updateByPrimaryKey(user_t record);
}